# Generated by Django 4.1.7 on 2023-03-16 17:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Owner',
            new_name='Person',
        ),
        migrations.AddField(
            model_name='job',
            name='person',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='home.person'),
        ),
        migrations.AddField(
            model_name='school',
            name='person',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='home.person'),
        ),
        migrations.AddField(
            model_name='skill',
            name='person',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='home.person'),
        ),
    ]
