# Generated by Django 4.1.7 on 2023-03-16 23:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_rename_owner_person_job_person_school_person_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='objective',
            field=models.CharField(max_length=600),
        ),
    ]
