# Generated by Django 4.1.7 on 2023-03-17 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_project_short_description'),
        ('home', '0003_alter_person_objective'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='job',
            name='person',
        ),
        migrations.RemoveField(
            model_name='school',
            name='person',
        ),
        migrations.RemoveField(
            model_name='skill',
            name='person',
        ),
        migrations.AddField(
            model_name='person',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='person',
            name='jobs',
            field=models.ManyToManyField(blank=True, to='home.job'),
        ),
        migrations.AddField(
            model_name='person',
            name='projects',
            field=models.ManyToManyField(blank=True, to='projects.project'),
        ),
        migrations.AddField(
            model_name='person',
            name='schools',
            field=models.ManyToManyField(blank=True, to='home.school'),
        ),
        migrations.AddField(
            model_name='person',
            name='skills',
            field=models.ManyToManyField(blank=True, to='home.skill'),
        ),
    ]
