# Generated by Django 4.1.7 on 2023-03-18 02:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_job_end_date_job_start_date_school_graduation_year'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='phone',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='person',
            name='site',
            field=models.URLField(blank=True, null=True),
        ),
    ]
