# Generated by Django 4.1.7 on 2023-03-18 03:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_person_phone_person_site'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='site',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
